# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortit',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='shortit',
            name='notes',
            field=models.TextField(default='Nothing to add here'),
        ),
    ]
